feat(i18n): zh-TW translation typo corrected
reuixiy/hugo-theme-meme pull request #272
Opened 2020-11-27 16:25 UTC by KunoiSayami

2020-11-27 16:47 UTC, reuixiy requested changes
Thanks!

2020-11-27 16:47 UTC, reuixiy commented on README.zh-tw.md
> +MemE 廣泛地使用了 [CSS 變數](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) 和 [let 宣告](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)。這些特性被以下
Could you remove this extra whitespace?

2020-11-27 17:26 UTC, KunoiSayami commented on README.zh-tw.md
> +MemE 廣泛地使用了 [CSS 變數](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) 和 [let 宣告](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)。這些特性被以下
Fixed

2020-11-28 01:20 UTC, reuixiy approved these changes

2020-11-28 01:21 UTC, merged

2020-11-28 03:29 UTC, KunoiSayami commented
Forget add file to index... Sorry

2020-11-28 03:39 UTC, reuixiy commented
Nah, it's ok :)

Thanks for your contribution!