feat. support hideInHomePage front matter
reuixiy/hugo-theme-meme pull request #377
Opened 2022-04-22 16:36 UTC by zjc17

提供支持将文章在首页因此（不想上首页）的选项

```
---
hideInHomePage: true
---
```

不填充时默认允许展示

2022-04-23 12:48 UTC, reuixiy requested changes

2022-04-23 12:48 UTC, reuixiy commented on layouts/partials/pages/home-posts.html
> +            (where .Site.RegularPages ".Params.hideInHomePage" "ne" true)
不知道能不能避免这样的查询嵌套，将 `.Params.hideInHomePage` 放到查询外面作为判断条件为 `$paginator` 赋值？

2022-04-23 12:48 UTC, reuixiy commented on layouts/partials/pages/home-posts.html
> +            (where .Site.RegularPages ".Params.hideInHomePage" "ne" true)
不知道能不能避免这样的查询嵌套，将 `.Params.hideInHomePage` 放到查询外面作为判断条件为 `$paginator` 赋值？

2022-04-23 12:50 UTC, reuixiy commented on layouts/partials/pages/home-posts.html
> +            (where .Site.RegularPages ".Params.hideInHomePage" "ne" true)
这样的话只有需要这个新增特性的用户，才会执行额外的查询

2022-04-24 12:36 UTC, zjc17 commented on layouts/partials/pages/home-posts.html
> +            (where .Site.RegularPages ".Params.hideInHomePage" "ne" true)
我没有找到 `hugo` 针对where多种条件的语法，或许可以

```
{{ $pages :=  where .Site.RegularPages ".Params.hideInHomePage" "ne" true}}
{{ $pages := where $pages "Section" "in" .Site.Params.mainSections }}
{{ $paginator := .Paginate ($pages) }}
```
但并没有解决查询嵌套的问题。

我在本地测试了一下，确实会影响性能（本以为或许有自动优化）。

我目前想到的方案是，在config内提供开关 `CustomFontMatters: ["hideInHomePage"]`，只有显式声明解析才在渲染时再次查询，不知道是否可以接受。

2022-04-24 16:51 UTC, reuixiy commented on layouts/partials/pages/home-posts.html
> +            (where .Site.RegularPages ".Params.hideInHomePage" "ne" true)
是的，需要在 config.toml 中新增一个全局开关（好久没动主题的代码，没注意到你写的是 `.Params.hideInHomePage` 而不是 `.Site.Params.hideInHomePage`）

也许可以这样写：

```
$pages := where .Site.RegularPages "Section" "in" .Site.Params.mainSections
{{ if .Site.Params.hideInHomePage }}
    {{ $pages = where $pages ".Params.hideInHomePage" "ne" true }}
{{ end }}
{{ $paginator := .Paginate $pages }}
```

2023-01-01 14:44 UTC, reuixiy approved these changes

2023-01-01 14:47 UTC, reuixiy commented
使用方法：

1. 在 config.toml 开启 `enableHideInHomepage`
2. 在需要的文章加上 Front Matter `hideInHomepage = true`（TOML）或 `hideInHomepage: true`（YAML）

2023-01-01 14:48 UTC, merged